flowchart TD
    S0[Substantial type]

    S0 --> S_CA{Concrete or \nAbstract?}

    %% ABSTRACT SUBSTANTIALS
    S_CA -->|Abstract| ABST[Abstract Type]
    ABST --> ABST_Q{Fixed value \nspace?}
    ABST_Q -->|Yes| ENUM[Enumeration]
    ABST_Q -->|No| DT[Datatype]

    %% CONCRETE SUBSTANTIALS
    S_CA -->|Concrete| SS{"Sortal?\n(identity providing)"}

    SS -->|Yes| S1{"Rigid?\n(non-changeable)"}
    SS -->|No| M_X{"Rigid,\nsemi-rigid,\nnon-rigid?\n(changeability)"}

    %% Sortals
    S1 -->|Yes| RG{Ultimate \nsortal \nor \nsubkind?}
    S1 -->|No| DR{Relationally\ndependent?}

    RG -->|Subkind| SK[Subkind]
    RG -->|Ultimate sortal| US{Object/\ncollective/\nquantity?}
    US -->|Object| KND[Kind]
    US -->|Collective| COL[Collective]
    US -->|Quantity| QTY["Quantity\n(portion)"]

    DR -->|Yes| RO[Role]
    DR -->|No| PH[Phase]

    %% Non-Sortals (Mixins)
    M_X -->|Rigid| CAT[Category]
    M_X -->|Semi-rigid| MIX[Semi-Rigid Mixin]
    M_X -->|Non-rigid| M_DX{Relationally\ndependent?}

    M_DX -->|Yes| RMX[RoleMixin]
    M_DX -->|No| PMX[PhaseMixin]

    %% EXAMPLE BOXES + LINKS
    DT_ex("e.g., Number, \nString, \nDate"):::example
    DT --> DT_ex

    ENUM_ex("e.g., Color(Red, Blue, Green), \nGender(Male, Female)"):::example
    ENUM --> ENUM_ex

    KND_ex("e.g., Table, Spoon, Person"):::example
    KND --> KND_ex

    SK_ex("e.g., ArabicaCoffee, CoffeeSpoon, Man"):::example
    SK --> SK_ex

    COL_ex("e.g., BasketOfBread, KitchenTeam, Forest"):::example
    COL --> COL_ex

    QTY_ex("e.g., Water, Coffee, Gold"):::example
    QTY --> QTY_ex

    CAT_ex("e.g., Furniture, Cutlery"):::example
    CAT --> CAT_ex

    MIX_ex("e.g., Animal, InsuredObject"):::example
    MIX --> MIX_ex

    RMX_ex("e.g., Customer, Tenant"):::example
    RMX --> RMX_ex

    PMX_ex("e.g., Fresh/Stale object, \nLiving/Dead animal"):::example
    PMX --> PMX_ex

    RO_ex("e.g., Student, Employee"):::example
    RO --> RO_ex

    PH_ex("e.g., Child, Adult"):::example
    PH --> PH_ex

    %% CLASSES
    classDef example fill:#BBBBBB,stroke:#111827,stroke-width:1px,color:#ffffff;
    classDef generic fill:#ffffff,stroke:#333,stroke-width:2px,color:#000;
    classDef substantial fill:#dcfce7,stroke:#dcfce7,stroke-width:2px,color:#000;
    classDef substantialId fill:#dcfce7,stroke:#16a34a,stroke-width:2px,color:#000;
    classDef substantialNonId fill:#dcfce7,stroke:#16a34a,stroke-width:2px,stroke-dasharray: 5 3,color:#000;
    classDef abstract fill:#f3f4f6,stroke:#9ca3af,stroke-width:2px,color:#000;

    %% generic / neutral nodes
    class S_CA,ABST_Q,SS,S1,M_X,RG,US,DR,M_SR,M_DX generic;

    %% substantial subtree colors
    class KND,COL,QTY substantialId;
    class SK,RO,PH substantialNonId;
    class S0,CAT,RMX,PMX,MIX substantial;
    class ABST,DT,ENUM abstract;