flowchart TD
    S0[Substantial type]

    %% CONCRETE SUBSTANTIALS
    S0 --> SS{"Sortal?\n(identity providing)"}

    SS -->|Yes| S1{"Rigid?\n(non-changeable)"}
    SS -->|No| M_X{"Rigid,\nsemi-rigid,\nnon-rigid?\n(changeability)"}

    %% Sortals
    S1 -->|Rigid| RG{Ultimate \nsortal \nor \nsubkind?}
    S1 -->|Anti-rigid| DR{Relationally\ndependent?}

    RG -->|Subkind| SK[Subkind]
    RG -->|Ultimate sortal| US{Object/\ncollective/\nquantity?}
    US -->|Object| KND[Kind]
    US -->|Collective| COL[Collective]
    US -->|Quantity| QTY["Quantity\n(portion)"]

    DR -->|Yes| RO[Role]
    DR -->|No| PH[Phase]

    %% Non-Sortals (Mixins)
    M_X -->|Rigid| CAT[Category]
    M_X -->|Semi-rigid| MIX[Semi-Rigid Mixin]
    M_X -->|Anti-rigid| M_DX{Relationally\ndependent\nor intrinsic?}

    M_DX -->|Relational| RMX[RoleMixin]
    M_DX -->|Intrinsic| PMX[PhaseMixin]

    %% EXAMPLE BOXES + LINKS
    KND_ex("e.g., Person, BreakfastPlace, \nSupplierCompany"):::example
    KND --> KND_ex

    SK_ex("e.g., ArabicaCoffeeBeanBatch, \nFamilyRunBreakfastPlace"):::example
    SK --> SK_ex

    COL_ex("e.g., StaffTeam, \nSupplierConsortium"):::example
    COL --> COL_ex

    QTY_ex("e.g., Coffee, Milk, Batter"):::example
    QTY --> QTY_ex

    CAT_ex("e.g., PhysicalObject, \nCommercialEstablishment"):::example
    CAT --> CAT_ex

    MIX_ex("e.g., SkilledWorker, \nInsuredAsset"):::example
    MIX --> MIX_ex

    RMX_ex("e.g., ServiceProvider, FoodBuyer"):::example
    RMX --> RMX_ex

    PMX_ex("e.g., AvailableResource, \nHeatedConsumable"):::example
    PMX --> PMX_ex

    RO_ex("e.g., Cook, Customer, \nEmployee, Employer"):::example
    RO --> RO_ex

    PH_ex("e.g., Child, Adult, \nSenior"):::example
    PH --> PH_ex

    %% CLASSES
    classDef example fill:#BBBBBB,stroke:#111827,stroke-width:1px,color:#ffffff;
    classDef generic fill:#ffffff,stroke:#333,stroke-width:2px,color:#000;
    classDef substantial fill:#dcfce7,stroke:#dcfce7,stroke-width:2px,color:#000;
    classDef substantialId fill:#dcfce7,stroke:#16a34a,stroke-width:2px,color:#000;
    classDef substantialNonId fill:#dcfce7,stroke:#16a34a,stroke-width:2px,stroke-dasharray: 5 3,color:#000;

    %% generic / neutral nodes
    class SS,S1,M_X,RG,US,DR,M_SR,M_DX generic;

    %% substantial subtree colors
    class KND,COL,QTY substantialId;
    class SK,RO,PH substantialNonId;
    class S0,CAT,RMX,PMX,MIX substantial;